################################################################################
#                                                                              #
# Jekyll Configuration Settings                                                #
#                                                                              #
################################################################################

baseurl: jekyll4-theme-optima

permalink: pretty

plugins:
  - jekyll-archives

timezone: America/New_York
