################################################################################
#                                                                              #
# Jekyll Configuration Settings                                                #
#                                                                              #
################################################################################

timezone: America/New_York

plugins:
  - jekyll-archives
