################################################################################
#                                                                              #
# Jekyll Configuration Settings                                                #
#                                                                              #
################################################################################

baseurl: /jekyll4-theme-optima

permalink: /:categories/:year-:month-:day-:title/

defaults:
  - scope:
      path: "notes"
      type: posts
    values:
      permalink: notes/:title/

excerpt_separator: "<!-- more -->"

plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

remote_theme: briandrum/jekyll4-theme-optima

timezone: America/New_York

url: https://briandrum.github.io

# Set to true to generate future-date posts
# future: true

################################################################################
#                                                                              #
# jekyll-seo-tag                                                               #
#                                                                              #
################################################################################

title: Optima
# tagline:
description: "Optima dies … prima fugit"
# url:
# author:
# facebook:
#   app_id: 1234
#   publisher: 1234
#   admins: 1234
# logo:
# social:
#   name: Optima
#   links:
#     - https://www.facebook.com/optima
#     - https://www.linkedin.com/in/optima
#     - https://github.com/optima
#     - https://keybase.io/optima
# webmaster_verifications:
#   google: 1234
#   bing: 1234
#   alexa: 1234
#   yandex: 1234
#   baidu: 1234
#   facebook: 1234

################################################################################
#                                                                              #
# Well-known                                                                   #
#                                                                              #
################################################################################

include: [".well-known"]

################################################################################
#                                                                              #
# Jekyll Archives                                                              #
#                                                                              #
################################################################################

jekyll-archives:
  enabled:
    - month
    - tags
  layouts:
    month: archive
    tag: archive
  permalinks:
    month: '/archives/:year-:month/'
    tag: '/tags/:name/'

################################################################################
#                                                                              #
# Jekyll Paginate v2                                                           #
#                                                                              #
################################################################################

pagination:
  enabled: true
  per_page: 10
  permalink: '/:num/'
  title: ':title - page :num of :max'
  limit: 0

################################################################################
#                                                                              #
# Optima Theme Configuration Settings                                          #
#                                                                              #
################################################################################

optima:
  # Optima date formats
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to
  # customize these.
  #
  time_and_date_short_format: "%-I:%M %P - %b %-d, %Y"
  date_long_format: "%B %-d, %Y"
  date_short_format: "%b %-d, %Y"

  # Features
  #
  features:
    plausible_analytics:
      enabled: true
      domain: briandrum.github.io

  # Plausible analytics: https://plausible.io/
  #
  plausible_analytics: briandrum.github.io

  # post_categories:

    # articles:
      # enabled: true

    # journal:
      # enabled: true

    # notes:
      # enabled: true

  # If you want to link only specific pages in your header, uncomment this and
  # add the path to the pages in order as they should show up.
  #
  header_pages:
    - notes
    - journal
    - articles
    - pages/now.md
    - pages/about.md
    - pages/archives.md
    - pages/search.md

  # Footer
  #
  description_title: "About"

  # If you want to link only specific pages in your footer, uncomment this and
  # add the path to the pages in order as they should show up.
  #
  footer_pages_title: "Here"
  footer_pages:
    - pages/home.md
    - notes
    - journal
    - articles
    - pages/now.md
    - pages/about.md
    - pages/archives.md
    - pages/tags.md
    - pages/search.md
    - pages/analytics.md

  # Generate social links in footer.
  #
  social_links_title: "Keep in touch"
  social_links:
    - { platform: Bluesky,   symbol_id: bluesky,   view_box: "0 0 576 512", user_name: "@bsky.app",  user_url: "https://bsky.app/profile/bsky.app" }
    - { platform: Dribbble,  symbol_id: dribbble,  view_box: "0 0 512 512", user_name: "@dribbble",  user_url: "https://dribbble.com/dribbble" }
    - { platform: Facebook,  symbol_id: facebook,  view_box: "0 0 512 512", user_name: "@facebook",  user_url: "https://www.facebook.com/facebook" }
    - { platform: Flickr,    symbol_id: flickr,    view_box: "0 0 448 512", user_name: "@flickr",    user_url: "https://www.flickr.com/photos/flickr" }
    - { platform: GitHub,    symbol_id: github,    view_box: "0 0 496 512", user_name: "@github",    user_url: "https://github.com/github" }
    - { platform: Instagram, symbol_id: instagram, view_box: "0 0 448 512", user_name: "@instagram", user_url: "https://www.instagram.com/instagram" }
    - { platform: LinkedIn,  symbol_id: linkedin,  view_box: "0 0 448 512", user_name: "@linkedin",  user_url: "https://www.linkedin.com/in/linkedin" }
    - { platform: Mastodon,  symbol_id: mastodon,  view_box: "0 0 448 512", user_name: "@mastodon",  user_url: "https://mastodon.social/@Mastodon" }
    - { platform: Telegram,  symbol_id: telegram,  view_box: "0 0 496 512", user_name: "@telegram",  user_url: "https://t.me/telegram" }
    - { platform: Threads,   symbol_id: threads,   view_box: "0 0 448 512", user_name: "@threads",   user_url: "https://www.threads.net/@threads" }
    - { platform: YouTube,   symbol_id: youtube,   view_box: "0 0 576 512", user_name: "@youtube",   user_url: "https://www.youtube.com/youtube" }

  # Generate other links in footer.
  #
  other_links_title: "Elsewhere"
  other_links:
  #   - { site_name: "briandrum.com", site_url: "https://briandrum.com" }
    - { site_name: "councilmandrum.net", site_url: "https://councilmandrum.net" }
    - { site_name: "sugarandfrogs.com", site_url: "https://www.sugarandfrogs.com" }
    - { site_name: "codes.forchagrin.com", site_url: "https://codes.forchagrin.com" }
