################################################################################
#                                                                              #
# Jekyll Configuration Settings                                                #
#                                                                              #
################################################################################

baseurl: /jekyll4-theme-optima

permalink: /:categories/:year-:month-:day-:title/

defaults:
  - scope:
      path: "notes"
      type: posts
    values:
      permalink: notes/:title/

excerpt_separator: "<!-- more -->"

plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

remote_theme: briandrum/jekyll4-theme-optima

timezone: America/New_York

url: https://briandrum.github.io

# Set to true to generate future-date posts
# future: true

################################################################################
#                                                                              #
# jekyll-seo-tag                                                               #
#                                                                              #
################################################################################

title: Optima
# tagline:
description: "Optima dies … prima fugit"
# url:
# author:
# facebook:
#   app_id: 1234
#   publisher: 1234
#   admins: 1234
# logo:
# social:
#   name: Optima
#   links:
#     - https://www.facebook.com/optima
#     - https://www.linkedin.com/in/optima
#     - https://github.com/optima
#     - https://keybase.io/optima
# webmaster_verifications:
#   google: 1234
#   bing: 1234
#   alexa: 1234
#   yandex: 1234
#   baidu: 1234
#   facebook: 1234

################################################################################
#                                                                              #
# Well-known                                                                   #
#                                                                              #
################################################################################

include: [".well-known"]

################################################################################
#                                                                              #
# Jekyll Archives                                                              #
#                                                                              #
################################################################################

jekyll-archives:
  enabled:
    - year
    - month
    - day
    - tags
  layouts:
    year: archive-year
    month: archive-month
    day: archive-day
    tag: archive-tag
  permalinks:
    year: '/archives/:year/'
    month: '/archives/:year/:month/'
    day: '/archives/:year/:month/:day/'
    tag: '/tags/:name/'

################################################################################
#                                                                              #
# Jekyll Paginate v2                                                           #
#                                                                              #
################################################################################

pagination:
  enabled: true
  per_page: 10
  permalink: '/:num/'
  title: ':title - page :num of :max'
  limit: 0

################################################################################
#                                                                              #
# Optima Theme Configuration Settings                                          #
#                                                                              #
################################################################################

optima:
  # Optima date formats
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to
  # customize these.
  #
  time_and_date_short_format: "%-I:%M %P - %b %-d, %Y"
  date_long_format: "%B %-d, %Y"

  # Features
  #
  features:
    plausible_analytics:
      enabled: true
      domain: briandrum.github.io

  # Plausible analytics: https://plausible.io/
  #
  plausible_analytics: briandrum.github.io

  # post_categories:

    # articles:
      # enabled: true

    # journal:
      # enabled: true

    # notes:
      # enabled: true

  # If you want to link only specific pages in your header, uncomment this and
  # add the path to the pages in order as they should show up.
  #
  header_pages:
    - notes
    - journal
    - articles
    - pages/now.md
    - pages/about.md
    - pages/archives.md
    - pages/search.md

  # Footer
  #
  description_title: "About"

  # If you want to link only specific pages in your footer, uncomment this and
  # add the path to the pages in order as they should show up.
  #
  footer_pages_title: "Here"
  footer_pages:
    - pages/home.md
    - notes
    - journal
    - articles
    - pages/now.md
    - pages/about.md
    - pages/archives.md
    - pages/search.md
    - pages/analytics.md

  # Generate social links in footer.
  #
  social_links_title: "Keep in touch"
  social_links:
  #   - { platform: devto,          user_name: "jekyll",                  user_url: "https://dev.to/jekyll" }
  #   - { platform: dribbble,       user_name: "jekyll",                  user_url: "https://dribbble.com/jekyll" }
  #   - { platform: facebook,       user_name: "jekyll",                  user_url: "https://www.facebook.com/jekyll" }
  #   - { platform: flickr,         user_name: "jekyll",                  user_url: "https://www.flickr.com/photos/jekyll" }
    - { platform: github,         user_name: "jekyll4-theme-optima",      user_url: "https://github.com/briandrum/jekyll4-theme-optima" }
  #   - { platform: google_scholar, user_name: "jekyll",                  user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #   - { platform: instagram,      user_name: "jekyll",                  user_url: "https://www.instagram.com/jekyll" }
  #   - { platform: keybase,        user_name: "jekyll",                  user_url: "https://keybase.io/jekyll" }
    - { platform: linkedin,       user_name: "jekyll",                  user_url: "https://www.linkedin.com/in/jekyll" }
    - { platform: mastodon,       user_name: "@minima@mastodon.social", user_url: "https://mastodon.social/@minima" }
  #   - { platform: microdotblog,   user_name: "jekyll",                  user_url: "https://micro.blog/jekyll" }
  #   - { platform: pinterest,      user_name: "jekyll",                  user_url: "https://www.pinterest.com/jekyll" }
  #   - { platform: stackoverflow,  user_name: "jekyll",                  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
  #   - { platform: telegram,       user_name: "jekyll",                  user_url: "https://t.me/jekyll" }
    - { platform: twitter,        user_name: "@jekyllrb",                user_url: "https://twitter.com/jekyllrb" }
  #   - { platform: youtube,        user_name: "jekyll",                  user_url: "https://www.youtube.com/jekyll" }

  # Generate other links in footer.
  #
  other_links_title: "Elsewhere"
  other_links:
  #   - { site_name: "briandrum.com", site_url: "https://briandrum.com" }
    - { site_name: "councilmandrum.net", site_url: "https://councilmandrum.net" }
    - { site_name: "sugarandfrogs.com", site_url: "https://www.sugarandfrogs.com" }
    - { site_name: "codes.forchagrin.com", site_url: "https://codes.forchagrin.com" }
